#!/bin/bash
# Post installation script

createFlag() {
    mkdir -p "$HOME/.config/crunchbang"
    touch "$HOME/.config/crunchbang/cb-welcome"
}

runInTerminal() {
    x-terminal-emulator -e 'cb-welcome'
    exit 0
}

# Usage: installPage title text package...
installPage() {
    clear

    say "----------------------[ screen $STEP of $STEPS ]----------------------"
    say
    say "INSTALL ${1^^}"
    say '------------------'
    say "$2"
    say
    say 'If you choose to do this, the following packages will be installed:'
    say "  ${@:3}"
    say
    say 'Note: additional packages listed as dependencies will also be installed.'
    say
    prompt "  Would you like to install $1" &&
        sudo apt-get install -y "${@:3}"
}

# First run
if [[ $1 = '--firstrun' ]]; then
    [[ -d /live/overlay || -e $HOME/.config/crunchbang/cb-welcome || ! $(groups) =~ ( |^)sudo( |$) ]] && exit 1
    runInTerminal
fi

# Open in terminal
if [[ $1 = '--open' ]]; then
    runInTerminal
fi

createFlag

if [[ ! $(groups) =~ ( |^)sudo( |$) ]]; then
  say 'Error: must be a member of the sudo group to run this script.' # TODO 'root' user is not a member of the sudo group. Is it meant to restrict root from executing this script?
  exit 1
fi

LIBDIR='/usr/lib/lib-cb-welcome'

if ! . cb-include.cfg 2> /dev/null; then
    echo '  Failed to locate cb-include.cfg in PATH' >&2
    exit 1
fi

# Run through steps
STEPS_BASIC=('apt-update' 'apt-dist-upgrade' 'install-printer-packages' 'install-java-packages' 'install-libreoffice' 'devel')
STEPS_DEVEL=('devel-install-version-control-tools' 'devel-install-ssh-server' 'devel-install-lamp-stack' 'devel-install-packaging-tools')
STEP=1
(( STEPS = ${#STEPS_BASIC[@]} + ${#STEPS_DEVEL[@]} + 2 )) # 2 is intro and fini

. "$LIBDIR/intro"
clear
connectiontest

for curStep in "${STEPS_BASIC[@]}"; do
    ((STEP++))
    . "$LIBDIR/$curStep"
done

if [[ $DEVEL ]]; then
    for curStep in "${STEPS_DEVEL[@]}"; do
        ((STEP++))
        . "$LIBDIR/$curStep"
    done
fi

. "$LIBDIR/fini"

exit 0
